expvoucher:
  spawn_on_death: true
  # Should exp vouchers spawn on death
  # ----------------------------------
  value: 1
  # How much of the player's exp should be saved?
  # Value 0.1 -> 1 (all)
  # ---------------------
  soulbind: true
  # Should exp vouchers spawned by dying be soulbound
  # -------------------------------------------------
  enable_command: true
  # Should /giveexpvoucher be enabled?
# =======================================
removeinfos:
  enable_command: true
  # Should /removeinfos be enabled?
# =======================================
gtp:
  enable_command: true
  # Should /gtp be enabled?
# =======================================
keepinventory:
  enable_command: true
  # Should /keepinventory be enabled?
# =======================================
opengrave:
  enable_command: true
  # Should /opengrave be enabled?
  # --------------------------------
  enable_force: true
  # Should "/opengrave --force" be enabled?
# =======================================
soulbound:
  enable_command: true
  # Should /soulbind be enabled?
  # ----------------------------
  prevent_dropping: false
  # Should dropping soulbound items be impossible
# ===============================================
unbreakable_graves: true
# Should graves be unbreakable
# ============================
death_cause:
  pvp: no_override
  # pvp override
  # options; no_override, open, normal, keep_inventory
  # ---------------------------------------------------

  # Last damage cause
  # options; open, normal, keep_inventory
  BLOCK_EXPLOSION: normal
  CONTACT: normal
  CRAMMING: normal
  CUSTOM: normal
  DRAGON_BREATH: normal
  DROWNING: normal
  DRYOUT: normal
  ENTITY_ATTACK: normal
  ENTITY_EXPLOSION: normal
  ENTITY_SWEEP_ATTACK: normal
  FALL: normal
  FALLING_BLOCK: normal
  FIRE: normal
  FIRE_TICK: normal
  FLY_INTO_WALL: normal
  HOT_FLOOR: normal
  LAVA: normal
  LIGHTNING: normal
  MAGIC: normal
  POISON: normal
  PROJECTILE: normal
  STARVATION: normal
  SUFFOCATION: normal

  SUICIDE: normal
  # NOTE This one seems to be unused.
  # NOTE For /kill VOID is used instead.

  THORNS: normal
  VOID: normal
  WITHER: normal
  # ----------------------------------------
# =================================
# The end.
# That's it
# =================================
