expvoucher:
  spawn_on_death: true
  value: 1
  # How much of the player's exp should be saved?
  # Value 0.1 -> 1 (all)
  enable_command: true
  # Should /giveexpvoucher be enabled?
removeinfos:
  enable_command: true
  # Should /removeinfos be enabled?
gtp:
  enable_command: true
  # Should /gtp be enabled?
keepinventory:
  enable_command: true
  # Should /keepinventory be enabled?
